.\" See COPYING file for copyright and license details.
.TH GETBNBOOK 1 getbnbook\-VERSION
.SH NAME
getbnbook \- downloads books from barnes and noble
.SH SYNOPSIS
.B getbnbook
.RB [-n]
.RB isbn13
.SH DESCRIPTION
getbnbook downloads pages of books from barnes and noble's
"book viewer" service. Some pages are not available, in
which case they will be skipped.
.SH OPTIONS
.TP
.B \-n
Downloads from page numbers given on stdin (one number per
line).
.TP
.B isbn13
is the ISBN-13 number of a book. It is 13 digits long.
.SH EXAMPLES
.TP
.B download all available pages of a book
getbnbook 9780060850524
.TP
.B download the first 20 pages of a book
seq 20 | getbnbook -n 9780060850524
.SH SEE ALSO
.IR getabook (1),
.IR getgbook (1),
.IR getxbookgui (1)
